export { default as IcBack } from './IcBack';
export { default as IcCalendar } from './IcCalendar';
export { default as IcClock } from './IcClock';
export { default as IcDownarrow } from './IcDownarrow';
export { default as IcEdit } from './IcEdit';
export { default as IcMike } from './IcMike';
export { default as IcPlus } from './IcPlus';
export { default as IcProfile } from './IcProfile';
export { default as IcUparrow } from './IcUparrow';
